//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pdf_project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public System.Guid id { get; set; }
        public string anywhereid { get; set; }
        public string backupcompany { get; set; }
        public string backupname { get; set; }
        public Nullable<System.DateTime> backupsince { get; set; }
        public Nullable<int> backupsize { get; set; }
        public bool cashifc { get; set; }
        public bool cashifcex { get; set; }
        public string cashname { get; set; }
        public bool ccardifc { get; set; }
        public string ccardname { get; set; }
        public bool channelmanagerifc { get; set; }
        public bool channelmanagerifcex { get; set; }
        public string channelmanagername { get; set; }
        public string city { get; set; }
        public bool cloud { get; set; }
        public bool cloudbackup { get; set; }
        public string cloudcompany { get; set; }
        public string cloudserver { get; set; }
        public Nullable<System.DateTime> cloudsince { get; set; }
        public string cloudtsplusserialno { get; set; }
        public Nullable<byte> cloudtsplususer { get; set; }
        public string cloudtsplusversion { get; set; }
        public Nullable<byte> clouduser { get; set; }
        public string contractpartner { get; set; }
        public string countryid { get; set; }
        public string countryiso { get; set; }
        public Nullable<byte> customertype { get; set; }
        public Nullable<System.DateTime> dateofpurchase { get; set; }
        public Nullable<byte> dealer { get; set; }
        public bool doorifc { get; set; }
        public string doorname { get; set; }
        public Nullable<byte> easystandpro { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public bool fibuifc { get; set; }
        public string fibuname { get; set; }
        public string freshdeskemail { get; set; }
        public bool hopewebifc { get; set; }
        public string hopewebifcid { get; set; }
        public Nullable<byte> hopewebifcversion { get; set; }
        public bool hotline { get; set; }
        public bool hotline24 { get; set; }
        public Nullable<System.DateTime> hotline24since { get; set; }
        public Nullable<System.DateTime> hotlinesince { get; set; }
        public string internet { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<System.DateTime> lastupdatecheck { get; set; }
        public bool licend { get; set; }
        public Nullable<System.DateTime> licenddate { get; set; }
        public Nullable<int> maxrooms { get; set; }
        public string name { get; set; }
        public string name1 { get; set; }
        public string name2 { get; set; }
        public Nullable<byte> netstations { get; set; }
        public bool nobigupdate { get; set; }
        public bool noupdate { get; set; }
        public Nullable<long> number { get; set; }
        public bool paytvifc { get; set; }
        public string phone { get; set; }
        public bool phoneifc { get; set; }
        public bool phoneifcex { get; set; }
        public string phonename { get; set; }
        public bool regcardifc { get; set; }
        public string regcardname { get; set; }
        public string serialno { get; set; }
        public string street { get; set; }
        public string streetno { get; set; }
        public string teamviewerid { get; set; }
        public string teamviewerpwd { get; set; }
        public bool updatemanu { get; set; }
        public bool updates { get; set; }
        public Nullable<System.DateTime> updatessince { get; set; }
        public string versionact { get; set; }
        public string versionlast { get; set; }
        public Nullable<byte> versiontype { get; set; }
        public string zip { get; set; }
        public bool feedback { get; set; }
        public string feedbackname { get; set; }
    }
}
