//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pdf_project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class kunden
    {
        public Nullable<double> kunr { get; set; }
        public string name1 { get; set; }
        public string name2 { get; set; }
        public string strasse { get; set; }
        public string land { get; set; }
        public string plz { get; set; }
        public string ort { get; set; }
        public Nullable<System.DateTime> kaufdat { get; set; }
        public string seriennr { get; set; }
        public Nullable<double> agentur { get; set; }
        public Nullable<double> version { get; set; }
        public bool shareware { get; set; }
        public Nullable<double> maxzimm { get; set; }
        public Nullable<double> verstand { get; set; }
        public Nullable<System.DateTime> verdatum { get; set; }
        public bool lizend { get; set; }
        public Nullable<System.DateTime> lizenddat { get; set; }
        public string email { get; set; }
        public bool hopeweb { get; set; }
        public string hopewebid { get; set; }
        public bool feedback { get; set; }
        public string aktversion { get; set; }
        public string lastcheck { get; set; }
        public bool CM { get; set; }
    }
}
